### PR TITLE
docs: add instructions to build a location path

### LINKED ISSUE #68: location_path helper method removed in v2.0.0 is not mentioned in the Migration Guide
The `location_path` helper method is not available in DataCatalogClient v2.0.0, although the [2.0.0 Migration Guide](https://github.com/googleapis/python-datacatalog/blob/master/UPGRADING.md#project-path-helper-methods) does not mention it. Is this the intended behavior starting from 2.0.0? If so, should I submit a PR to update the migration guide?

Thanks,

### PR DESCRIPTION
**Pull request by ricardolsmendes**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-datacatalog/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass - N/A
- [ ] Code coverage does not decrease (if any source code was changed) - N/A
- [x] Appropriate docs were updated (if necessary)

Fixes #68 🦕

### CODE REVIEW

**Comment by tswast** [comment]
Looks like these helpers were added back in https://github.com/googleapis/python-datacatalog/pull/64/files#diff-88240775a7bf30997273f4cd159e38bbff4ef74a98e065ec045706d3acf5f125R287

(To be released in 3.0 https://github.com/googleapis/python-datacatalog/pull/71)

**Comment by ricardolsmendes** [comment]
> Looks like these helpers were added back in https://github.com/googleapis/python-datacatalog/pull/64/files#diff-88240775a7bf30997273f4cd159e38bbff4ef74a98e065ec045706d3acf5f125R287
> 
> (To be released in 3.0 #71)

Thanks for letting me know, @tswast!

**Comment by ricardolsmendes** [comment]
Hey @tswast, I've tested v3.0.0 and the helper methods are back but with slightly different names, prefixed with `common_`: `common_billing_account_path`, `common_folder_path`, `common_location_path`, `common_location_path`, and `common_project_path`.

Maybe it's worth keeping this change to the v2.0,0 migration guide and write new instructions to the v3.0.0. WDYT? 🤔

**Comment by tswast** [comment]
Since 2.0 hasn't been out all that long, maybe we should update the guide to be from 1.0 to 3.0?

**Comment by ricardolsmendes** [comment]
> Since 2.0 hasn't been out all that long, maybe we should update the guide to be from 1.0 to 3.0?

Makes sense. I can work on this in a couple of days if that works for you.

**Comment by ricardolsmendes** [comment]
Closing this PR because I'm updating the upgrade guide to be from 1.0 to 3.0 in #77...

**Pull request closed without merging**
