### PR TITLE
fix: make datacatalog == datacatalog_v1

### LINKED ISSUE #116: v1beta1 is being used as the default alias instead of v1
```py
from google.cloud import datacatalog  # this should be 'datacatalog_v1' but is actually 'datacatalog_v1beta1'
from google.cloud import datacatalog_v1beta1
from google.cloud import datacatalog_v1
```
https://github.com/googleapis/python-datacatalog/blob/master/google/cloud/datacatalog/__init__.py#L18
https://github.com/googleapis/python-datacatalog/blob/4bfa587903105cb3de2272618374df0b04156017/synth.py#L28

The am planning on comparing the protos to determine if there are meaningful differences in the protos. If there are breaking changes, this would need to be done in a new major.

CC @tswast @steffnay

### PR DESCRIPTION
**Pull request by busunkim96**
Fixes #116

I have verified that v1beta1 -> v1 is additive, so this is *not*
a breaking change. See internal changelist 390485345 for the proto
level diff and successful run through the proto brekaing change detector

### CODE REVIEW

**Comment by busunkim96** [comment]
Hmm the failing samples seem to be **v1beta1**, which shouldn't be impacted by this change.

I see a mix of failures and passes on these tests on [continuous builds](https://fusion.corp.google.com/dashboard/findbuilds?search_pattern=python-datacatalog%2Fsamples%2F&project_types=&include_inactive_projects=false) on 8/12 and 8/13. Weirdly no periodic builds have failed.

**Comment by tseaver** [comment]
@busunkim96 The periodic builds roll back to run against the last released version of the repo, and the samples were added in PR #78, which landed after the `v3.4.0` release.

**Comment by tseaver** [comment]
I just ran the `v1beta1` samples locally, and see the same errors.  Could the backend have added a new constraint?  The [`Entry` docs](https://cloud.google.com/data-catalog/docs/reference/rpc/google.cloud.datacatalog.v1beta1#google.cloud.datacatalog.v1beta1.Entry) say:

| Field | Type | Description |
| ----- | ---- | ----------- |
| `user_specified_system` | `string` | This field indicates the entry's source system that Data Catalog does not integrate with. user_specified_system  strings must begin with a letter or underscore and can only contain  letters, numbers, and underscores; are case insensitive; must be at  least 1 character and at most 64 characters long. |

This patch gets the `v1beta1` samples passing for me:

```patch
--- a/samples/v1beta1/conftest.py
+++ b/samples/v1beta1/conftest.py
@@ -86,9 +86,16 @@ def entry(client, entry_group_name):
         now.strftime("%Y%m%d%H%M%S"), uuid.uuid4().hex[:8]
     )
     entry = datacatalog_v1beta1.CreateEntryRequest
-    entry = client.create_entry(
-        request={"parent": entry_group_name, "entry_id": random_entry_id, "entry": {"type_": "DATA_STREAM", "name": "samples_test_entry"}}
-    )
+    request = {
+        "parent": entry_group_name,
+        "entry_id": random_entry_id,
+        "entry": {
+            "type_": "DATA_STREAM",
+            "user_specified_system": "sample_system",
+            "name": "samples_test_entry",
+        },
+    }
+    entry = client.create_entry(request=request)
     yield entry.name
     client.delete_entry(request={"name": entry.name})
 
```

**Comment by busunkim96** [comment]
@tseaver Ah I forgot about the rolling back bit... 

The failures for the various Python versions didn't happen at the same time strangely, the [3.7 continuous](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-datacatalog%2Fsamples%2Fpython3.7%2Fcontinuous) failed this morning, but [3.6](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-datacatalog%2Fsamples%2Fpython3.6%2Fcontinuous) and [3.8](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-datacatalog%2Fsamples%2Fpython3.8%2Fcontinuous?search_pattern=python-datacatalog%2Fsamples%2F&include_inactive_projects=false) passed. 🤷‍♀️ 

@steffnay do you know of any recent changes to the Datacatalog v1beta1 surface?

**Comment by busunkim96** [comment]
After searching around internally I found internal changelist 387097607, which supposed to fix bug 194281199.

Explanation provided is the bug:

> Cannot set user-specified-system on update if it was not set at the moment of creation of a topic
>
> If one tries to set a user-specified-system for the first time via updating an entry, an error is thrown:
> ```Error 400: {
>   "error": {
>     "code": 400,
>     "message": "Changing managing system from MANUAL to ON_PREM is not allowed.",
>     "status": "INVALID_ARGUMENT"
>   }
> }```

It sounds to me like allowing an entry of that type without `user_specified_system` was a bug, and would result in the backend failing on subsequent calls. I'll update the sample with that patch.

**Review by tseaver — APPROVED** [review]

**Review by leahecole — APPROVED** [review]

**Review by dinagraves — APPROVED** [review]

**Pull request merged**
