### PR TITLE
docs(samples): Add sample for PolicyTagManagerClient.create_taxonomy

### LINKED ISSUE #36: There is no sample code for PolicyTagManagerClient.create_taxonomy
[PolicyTagManagerClient class was added to this library in version 0.5.0](https://googleapis.dev/python/datacatalog/latest/changelog.html#id6), but there is no sample code demonstrating how it works yet.

### PR DESCRIPTION
**Pull request by ricardolsmendes**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-datacatalog/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

Fixes #36 🦕

### CODE REVIEW

**Comment by ricardolsmendes** [comment]
The test created in https://github.com/googleapis/python-datacatalog/pull/37/files#diff-846e070615bad825160d9d5aae12529d will make `nox -s samples-2.7` and `nox -s samples-3.7` fail until https://github.com/googleapis/python-datacatalog/issues/33 is fixed.

**Comment by meredithslota** [comment]
#33 is still not fixed due to backend issues, we are keeping tabs on it internally.

**Review by tswast — CHANGES_REQUESTED** [review]
Apologies for the delay. I can hopefully review more thoroughly soon.

Could you please move this sample and tests to https://github.com/googleapis/python-datacatalog/tree/master/samples/snippets ? That will ensure it is getting tested by our latest samples templates.

**Comment by ricardolsmendes** [comment]
> Could you please move this sample and tests to https://github.com/googleapis/python-datacatalog/tree/master/samples/snippets ? That will ensure it is getting tested by our latest samples templates.

Hi @tswast, I've moved `create_taxonomy.py` and `create_taxonomy_test.py` to `samples/snippets`, but I'm not sure about what should I do with `samples/tests/conftest.py`. Also, I was not able to test the snippets locally. Could you advise, please?

**Comment by tswast** [comment]
> samples/tests/conftest.py

This file can also be moved to `samples/snippets/`. Latest guidelines are to have all test code in the same directory as the sample code.

> I was not able to test the snippets locally. Could you advise, please?

Do you still have nox installed? You should be able to `cd` to the `samples/snippets` directory and run `nox` from there. See https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md for a very detailed guide.

**Comment by tswast** [comment]
> (Snippet Bot): There is a possible violation for not having product prefix. `samples/snippets/create_taxonomy.py:18`, tag datacatalog_create_taxonomy_tag

This should be `data_catalog_ptm_create_taxonomy` to match https://github.com/GoogleCloudPlatform/golang-samples/blob/05c7ba5165b234994806cd96c789b6611100adad/datacatalog/snippets/policytagmanager/create_taxonomy.go#L17-L61

**Comment by tmatsuo** [comment]
@tswast is correct. The bot also thinks `data_catalog` is the correct region tag prefix.

**Comment by ricardolsmendes** [comment]
Thanks, @tswast and @tmatsuo!
I was able to successfully test the snippet with both `nox -s py-3.6 -- data_catalog_ptm_create_taxonomy_test.py` and `nox -s py-3.8 -- data_catalog_ptm_create_taxonomy_test.py`. Please let me know if I can help with anything else. Best,

**Comment by ricardolsmendes** [comment]
Please notice I needed to create a Taxonomy object using fixtures, so I can check its display name and delete it in the teardown stage. Different from other Data Catalog endpoints, that allow us to generate an id and provide the name when creating a resource, `create_taxonomy` seems to generate the id and hence the resource name, so I cannot rely on a previously known id to delete the resource. Makes sense? 🤔

**Review by tswast — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
